spring:
  messages:
    basename: i18n/messages
  application:
    name: SnappfoodTest
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: ${DB_URL}
    name: ${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  #    hikari:
  #      auto-commit: false
  h2:
    console:
      enabled: true
      path: "/db-ui"
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
springdoc:
  swagger-ui:
    operationsSorter: method
    path: "/swagger-ui.html"
  api-docs:
    path: "/api-docs"
snapfood:
  thirdparty:
    eta:
      url: https://run.mocky.io/v3/
---
server:
  port: 9876